In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.head()

labels       f_0       f_1       f_2       f_3       f_4       f_5  \
0       0 -2.033875  0.978446 -0.142131 -0.177117 -1.470684  1.669562   
1       1 -0.348835  0.294815 -0.557577 -2.020773 -1.234715  1.633930   
2       1  0.113248 -0.607726 -0.947791  0.830851  0.998291  0.498321   
3       0  1.223321 -0.479048 -1.925789  1.680377  0.021840 -1.453307   
4       0  0.160109  0.422684 -0.308029  0.227744  0.432854  0.608348   

        f_6       f_7       f_8  ...    f_1190    f_1191    f_1192    f_1193  \
0 -0.196530 -0.125239 -0.452284  ... -1.111266  0.716084  0.060039  0.301279   
1 -1.680658 -0.358146  0.166122  ...  0.735240  0.829781  1.521941  1.347946   
2 -1.493958  0.789572 -1.311018  ...  0.104698  0.616189 -1.035953  2.111387   
3  0.605559 -0.019024  1.065448  ...  0.360237 -1.957863 -0.123384  1.505329   
4  0.193832  1.035091 -0.538868  ...  0.416629  1.441766  0.212572 -0.994721   

     f_1194    f_1195    f_1196    f_1197    f_1198    f_1199  
0 -1.174846 -1.076498 -0.069452 -0.604012 -2.179176  0.558003  
1  0.754505  1.330642 -0.754453  0.582956  0.252671  1.495870  
2 -0.984415  1.148076 -1.433554  0.243372  0.170083  1.274795  
3  0.660290 -1.769443 -0.547756 -0.568122  0.244645  0.982116  
4  1.143999 -2.166923 -1.199248 -1.028636  0.752791  0.317169  

[5 rows x 1201 columns]

In [4]:
test = pd.read_csv('test.csv')

In [5]:
test.head()

id       f_0       f_1       f_2       f_3       f_4       f_5       f_6  \
0   1 -3.388242  0.868285 -0.427619 -0.678964 -1.625735  0.262761  1.243040   
1   2 -0.496920  0.952381  0.989040  0.451422  0.513516 -0.099658 -1.124326   
2   3  1.128369 -0.537951  2.544358  1.165254 -1.904994  0.776961 -0.495768   
3   4  0.051253  1.746814  0.681177  1.844524 -0.327977  1.226839 -0.085519   
4   5  1.423209 -0.983594 -1.694170  1.197507  1.044211  0.518777 -0.298612   

        f_7       f_8  ...    f_1190    f_1191    f_1192    f_1193    f_1194  \
0  1.537751 -0.352028  ... -0.776403 -0.662884 -0.257091 -1.168413  0.223260   
1  0.729430 -0.216224  ...  0.379635 -1.760084  1.125450 -0.328047 -0.880305   
2  0.060111 -1.418468  ...  1.165254 -1.373589 -0.483701 -0.964782 -0.869555   
3  0.379008 -1.003667  ... -0.442288 -2.794472 -0.763468 -0.789832 -0.113209   
4 -0.365174  0.738447  ... -2.624450 -3.200223  0.711422 -0.190394  0.337224   

     f_1195    f_1196    f_1197    f_1198    f_1199  
0 -0.482520 -0.085453 -0.382265 -0.539349 -1.682404  
1 -1.257607  0.964312  2.021104  0.655021 -0.423029  
2  0.066040 -0.444567 -0.531935 -0.878660  1.099488  
3 -2.703150 -2.058728  1.070627 -0.458045 -0.435825  
4 -1.656639  0.707360 -0.562290  1.471181 -0.192000  

[5 rows x 1201 columns]

In [6]:
df.shape

(5250, 1201)

In [7]:
test.shape

(2250, 1201)

In [8]:
df.isnull().sum()

labels    0
f_0       0
f_1       0
f_2       0
f_3       0
         ..
f_1195    0
f_1196    0
f_1197    0
f_1198    0
f_1199    0
Length: 1201, dtype: int64

In [9]:
df.nunique()

labels       2
f_0       5242
f_1       5244
f_2       5245
f_3       5247
          ... 
f_1195    5242
f_1196    5247
f_1197    5244
f_1198    5243
f_1199    5242
Length: 1201, dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5250 entries, 0 to 5249
Columns: 1201 entries, labels to f_1199
dtypes: float64(1200), int64(1)
memory usage: 48.1 MB


In [11]:
x = df.drop('labels' , axis=1)

In [12]:
y = df['labels']

In [13]:
submission = test['id']

In [14]:
test = test.drop('id' , axis =1)

In [15]:
output = pd.read_csv("solution_format.csv")
output.head()

id  labels
0   1       0
1   2       1
2   3       0
3   4       1
4   5       0

In [16]:
import csv

# Open the input CSV file
with open('solution_format.csv', 'r') as input_file:
    # Read the input CSV data
    reader = csv.reader(input_file)
    rows = list(reader)

# Determine the index of the column you want to delete
column_index = 1  # Replace with the actual index of the column to delete

# Remove the column from each row
for row in rows:
    del row[column_index]

# Open the output CSV file
with open('output.csv', 'w', newline='') as output_file:
    # Write the modified data to the output CSV file
    writer = csv.writer(output_file)
    writer.writerows(rows)


In [17]:
output = pd.read_csv('output.csv')
output.head()

id
0   1
1   2
2   3
3   4
4   5

SVM

In [18]:
from sklearn.svm import SVC
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Create an SVM classifier
svm = SVC()

# Train the SVM classifier
svm.fit(X_train, y_train)

# Make predictions on the test set
y_pred = svm.predict(X_test)

# Calculate the F1 score
f1 = f1_score(y_test, y_pred)

# Print the F1 score
print("F1 score:", f1)


F1 score: 0.6432160804020101


In [19]:
svm.fit(x,y)
ans = svm.predict(test)

In [20]:
ans

array([0, 0, 0, ..., 1, 0, 1], dtype=int64)

SVM with Polynomial of degree 2 kernel

In [25]:
from sklearn.svm import SVC
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler

# Perform feature scaling on the input data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create an SVM classifier
svm_classifier = SVC(kernel='poly', degree=2)

# Define the parameter grid for GridSearchCV
param_grid = {
    'C': [0.1, 1, 10],
    'gamma': [0.1, 0.01, 0.001],
}

# Create GridSearchCV instance
grid_search = GridSearchCV(estimator=svm_classifier, param_grid=param_grid, scoring='f1', cv=5)

# Fit the model with training data
grid_search.fit(X_train_scaled, y_train)

# Get the best model and its hyperparameters
best_model = grid_search.best_estimator_
best_params = grid_search.best_params_

# Make predictions on the test set
y_pred = best_model.predict(X_test_scaled)

# Calculate the F1 score of the model
f1 = f1_score(y_test, y_pred)
print("Best Hyperparameters:", best_params)
print("F1 score:", f1)


Best Hyperparameters: {'C': 0.1, 'gamma': 0.1}
F1 score: 0.6224489795918368


In [19]:
svm.fit(x,y)
ans = svm.predict(test)
ans

array([0, 0, 0, ..., 1, 0, 1], dtype=int64)

SVM with rbf kernel

In [27]:
from sklearn.svm import SVC
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler

# Perform feature scaling on the input data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create an SVM classifier
svm_classifier = SVC(kernel='rbf')

# Define the parameter grid for GridSearchCV
param_grid = {
    'C': [0.1, 1, 10],
    'gamma': [0.1, 0.01, 0.001],
}

# Create GridSearchCV instance
grid_search = GridSearchCV(estimator=svm_classifier, param_grid=param_grid, scoring='f1', cv=5)

# Fit the model with training data
grid_search.fit(X_train_scaled, y_train)

# Get the best model and its hyperparameters
best_model = grid_search.best_estimator_
best_params = grid_search.best_params_

# Make predictions on the test set
y_pred = best_model.predict(X_test_scaled)

# Calculate the F1 score of the model
f1 = f1_score(y_test, y_pred)
print("Best Hyperparameters:", best_params)
print("F1 score:", f1)


Best Hyperparameters: {'C': 10, 'gamma': 0.001}
F1 score: 0.6839622641509433


In [28]:
best_model.fit(x,y)
ans = best_model.predict(test)
ans

array([0, 0, 0, ..., 1, 0, 1], dtype=int64)

 Random forest

In [23]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import f1_score

# Load your dataset
X = df.drop('labels', axis=1).values
y = df['labels'].values

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the reduced parameter grid for GridSearchCV
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [None, 5],
    'min_samples_split': [2, 5],
}

# Create a Random Forest Classifier
rf_model = RandomForestClassifier()

# Create GridSearchCV instance
grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid, scoring='f1', cv=5)

# Fit the model with training data
grid_search.fit(X_train, y_train)

# Get the best model and its hyperparameters
best_model = grid_search.best_estimator_
best_params = grid_search.best_params_

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the F1 score
f1 = f1_score(y_test, y_pred)

print("Best Hyperparameters:", best_params)
print("F1 score:", f1)


Best Hyperparameters: {'max_depth': None, 'min_samples_split': 5, 'n_estimators': 100}
F1 score: 0.6205128205128205


In [23]:
rf_classifier.fit(x,y)
ans = rf_classifier.predict(test)
ans

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

XGBoost

In [26]:
import xgboost as xgb
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split, GridSearchCV

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create an XGBoost classifier
xgb_classifier = xgb.XGBClassifier()

# Define the parameter grid for GridSearchCV
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [3, 4, 5],
    'learning_rate': [0.1, 0.01]
}

# Create GridSearchCV instance
grid_search = GridSearchCV(estimator=xgb_classifier, param_grid=param_grid, scoring='f1', cv=5)

# Fit the model with training data
grid_search.fit(X_train, y_train)

# Get the best model and its hyperparameters
best_model = grid_search.best_estimator_
best_params = grid_search.best_params_

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the F1 score
f1 = f1_score(y_test, y_pred)

print("Best Hyperparameters:", best_params)
print("F1 score:", f1)


Best Hyperparameters: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200}
F1 score: 0.7074829931972789


In [44]:
best_model.fit(X,y)
ansxgb = best_model.predict(test)
ansxgb

C:\Users\Naina\anaconda3\lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(


array([0, 0, 0, ..., 1, 0, 1], dtype=int64)

In [45]:
import shutil

# Specify the path of the original CSV file
original_file = 'output.csv'

# Specify the path of the copy CSV file
copy_file = 'output_copy.csv'

# Make a copy of the original CSV file
shutil.copyfile(original_file, copy_file)

import pandas as pd

# Read the copied CSV file into a DataFrame
d = pd.read_csv(copy_file)
new_column = ansxgb

# Add the new column to the DataFrame
d['New Column'] = new_column
# Save the updated copy DataFrame as a new CSV file
d.to_csv(copy_file, index=False)


In [46]:
b = pd.read_csv('output_copy.csv')
b.head()

id  New Column
0   1           0
1   2           0
2   3           0
3   4           0
4   5           0

CNN

In [51]:
import numpy as np
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score

# Extract the feature matrix X and the label array y
X = df.drop('labels', axis=1).values
y = df['labels'].values

# Reshape the data into the appropriate format for CNN input
X = X.reshape(-1, 20, 20, 3)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the CNN architecture
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3), activation='leaky_relu', input_shape=(20, 20, 3)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dropout(0.5))
model.add(Dense(64, activation='leaky_relu'))
model.add(BatchNormalization())
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, batch_size=32, epochs=20, verbose=1)

# Make predictions on the test set
y_pred_probs = model.predict(X_test)
y_pred = (y_pred_probs > 0.5).astype(int)

# Calculate the F1 score
f1 = f1_score(y_test, y_pred)
print("F1 score:", f1)


Epoch 1/20
132/132 [==============================] - 1s 5ms/step - loss: 0.6307 - accuracy: 0.6936
Epoch 2/20
132/132 [==============================] - 1s 5ms/step - loss: 0.4295 - accuracy: 0.7986
Epoch 3/20
132/132 [==============================] - 1s 5ms/step - loss: 0.3666 - accuracy: 0.8236
Epoch 4/20
132/132 [==============================] - 1s 5ms/step - loss: 0.3567 - accuracy: 0.8300
Epoch 5/20
132/132 [==============================] - 1s 6ms/step - loss: 0.3334 - accuracy: 0.8417
Epoch 6/20
132/132 [==============================] - 1s 5ms/step - loss: 0.3223 - accuracy: 0.8483
Epoch 7/20
132/132 [==============================] - 1s 5ms/step - loss: 0.3115 - accuracy: 0.8531
Epoch 8/20
132/132 [==============================] - 1s 5ms/step - loss: 0.3032 - accuracy: 0.8581
Epoch 9/20
132/132 [==============================] - 1s 5ms/step - loss: 0.3021 - accuracy: 0.8576
Epoch 10/20
132/132 [==============================] - 1s 5ms/step - loss: 0.2871 - accuracy: 0.8669

In [52]:
test = test.values
# Reshape the test data into the appropriate format for CNN input
test = test.reshape(-1, 20, 20, 3)

# Predict labels for the test dataset
ans = model.predict(test)
y_pred = (ans > 0.5).astype(int)

# Print predicted labels
print("Predicted labels:", y_pred)


71/71 [==============================] - 0s 2ms/step
Predicted labels: [[0]
 [0]
 [0]
 ...
 [1]
 [0]
 [1]]


In [53]:
import shutil

# Specify the path of the original CSV file
original_file = 'output.csv'

# Specify the path of the copy CSV file
copy_file = 'output_copy.csv'

# Make a copy of the original CSV file
shutil.copyfile(original_file, copy_file)

import pandas as pd

# Read the copied CSV file into a DataFrame
d = pd.read_csv(copy_file)
new_column = y_pred

# Add the new column to the DataFrame
d['New Column'] = new_column
# Save the updated copy DataFrame as a new CSV file
d.to_csv(copy_file, index=False)


ANN

In [26]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.preprocessing import StandardScaler

# Load your dataset
X = df.drop('labels', axis=1).values
y = df['labels'].values

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Perform data normalization
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Create the ANN model
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(1200,)))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32, verbose=1)

# Make predictions on the test set
y_pred_probs = model.predict(X_test)
y_pred = (y_pred_probs > 0.5).astype(int)

# Calculate the F1 score
f1 = f1_score(y_test, y_pred)
print("F1 score:", f1)


Epoch 1/10
132/132 [==============================] - 1s 2ms/step - loss: 0.3604 - accuracy: 0.8298
Epoch 2/10
132/132 [==============================] - 0s 1ms/step - loss: 0.1511 - accuracy: 0.9483
Epoch 3/10
132/132 [==============================] - 0s 1ms/step - loss: 0.0508 - accuracy: 0.9912
Epoch 4/10
132/132 [==============================] - 0s 2ms/step - loss: 0.0120 - accuracy: 0.9998
Epoch 5/10
132/132 [==============================] - 0s 2ms/step - loss: 0.0030 - accuracy: 1.0000
Epoch 6/10
132/132 [==============================] - 0s 2ms/step - loss: 0.0015 - accuracy: 1.0000
Epoch 7/10
132/132 [==============================] - 0s 1ms/step - loss: 9.2146e-04 - accuracy: 1.0000
Epoch 8/10
132/132 [==============================] - 0s 1ms/step - loss: 6.2962e-04 - accuracy: 1.0000
Epoch 9/10
132/132 [==============================] - 0s 2ms/step - loss: 4.6118e-04 - accuracy: 1.0000
Epoch 10/10
33/33 [==============================] - 0s 893us/step
F1 score: 0.665377176

In [28]:
s = test
s = scaler.transform(s)
y_predd_probs = model.predict(s)
y_predd = (y_predd_probs > 0.5).astype(int)

71/71 [==============================] - 0s 983us/step


In [29]:
y_predd

array([[1],
       [1],
       [0],
       ...,
       [1],
       [0],
       [1]])

In [30]:
import shutil

# Specify the path of the original CSV file
original_file = 'output.csv'

# Specify the path of the copy CSV file
copy_file = 'output_copy.csv'

# Make a copy of the original CSV file
shutil.copyfile(original_file, copy_file)

import pandas as pd

# Read the copied CSV file into a DataFrame
d = pd.read_csv(copy_file)
new_column = y_predd

# Add the new column to the DataFrame
d['New Column'] = new_column
# Save the updated copy DataFrame as a new CSV file
d.to_csv(copy_file, index=False)


In [36]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.preprocessing import StandardScaler

# Load your dataset
X = df.drop('labels', axis=1).values
y = df['labels'].values

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Perform data normalization
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Create the ANN model
model2 = Sequential()
model2.add(Conv1D(filters=32, kernel_size=2, strides = 1, activation='relu', input_shape=(1200,1)))
model2.add(Conv1D(filters=64, kernel_size=3, strides = 2, activation='relu'))
model2.add(MaxPooling1D(pool_size=2))
model2.add(Flatten())
model2.add(Dense(64, activation='relu'))
model2.add(Dropout(rate = 0.5))
model2.add(Dense(1, activation='sigmoid'))

# Compile the model
model2.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model2.fit(X_train, y_train, epochs=10, batch_size=32, verbose=1)

# Make predictions on the test set
y_pred_probs = model2.predict(X_test)
y_pred = (y_pred_probs > 0.5).astype(int)

# Calculate the F1 score
f1 = f1_score(y_test, y_pred)
print("F1 score:", f1)


Epoch 1/10
132/132 [==============================] - 5s 31ms/step - loss: 0.4214 - accuracy: 0.7952
Epoch 2/10
132/132 [==============================] - 4s 31ms/step - loss: 0.3060 - accuracy: 0.8605
Epoch 3/10
132/132 [==============================] - 4s 32ms/step - loss: 0.2484 - accuracy: 0.8893
Epoch 4/10
132/132 [==============================] - 4s 34ms/step - loss: 0.1927 - accuracy: 0.9167
Epoch 5/10
132/132 [==============================] - 4s 33ms/step - loss: 0.1516 - accuracy: 0.9357
Epoch 6/10
132/132 [==============================] - 5s 36ms/step - loss: 0.1307 - accuracy: 0.9464
Epoch 7/10
132/132 [==============================] - 4s 33ms/step - loss: 0.0963 - accuracy: 0.9598
Epoch 8/10
132/132 [==============================] - 4s 34ms/step - loss: 0.0736 - accuracy: 0.9710
Epoch 9/10
132/132 [==============================] - 4s 32ms/step - loss: 0.0726 - accuracy: 0.9721
Epoch 10/10
33/33 [==============================] - 0s 10ms/step
F1 score: 0.7262357414448

In [37]:
test=scaler.transform(test)
y_predd_probs = model2.predict(test)
y_predd = (y_predd_probs >0.5).astype(int)
y_predd

71/71 [==============================] - 1s 9ms/step


array([[1],
       [1],
       [1],
       ...,
       [1],
       [0],
       [1]])

In [38]:
import shutil

# Specify the path of the original CSV file
original_file = 'output.csv'

# Specify the path of the copy CSV file
copy_file = 'output_copy.csv'

# Make a copy of the original CSV file
shutil.copyfile(original_file, copy_file)

import pandas as pd

# Read the copied CSV file into a DataFrame
d = pd.read_csv(copy_file)
new_column = y_predd

# Add the new column to the DataFrame
d['New Column'] = new_column
# Save the updated copy DataFrame as a new CSV file
d.to_csv(copy_file, index=False)


VGG16

In [56]:
import numpy as np
import tensorflow as tf
from keras.applications import VGG16
from keras.models import Model
from keras.layers import Flatten, Dense, Dropout, Input
from keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from keras.preprocessing.image import ImageDataGenerator

# Extract the feature matrix X and the label array y
X = df.drop('labels', axis=1).values
y = df['labels'].values

# Reshape the data into the appropriate format for CNN input
X = X.reshape(-1, 20, 20, 3)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Data augmentation
datagen = ImageDataGenerator(
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True
)
datagen.fit(X_train)

# Input layer with the desired input shape
input_layer = Input(shape=(20, 20, 3))

# Resize the input images to match the required input shape of VGG16
resized_input = tf.image.resize(input_layer, (224, 224))

# Load the pre-trained VGG16 model without the top layers
base_model = VGG16(weights='imagenet', include_top=False, input_tensor=resized_input)

# Freeze the layers of the base model
for layer in base_model.layers:
    layer.trainable = False

# Add your own layers on top of the base model
x = Flatten()(base_model.output)
x = Dense(128, activation='relu')(x)
x = Dropout(0.5)(x)
output = Dense(1, activation='sigmoid')(x)

# Create the model
model = Model(inputs=input_layer, outputs=output)

# Compile the model
model.compile(loss='binary_crossentropy', optimizer=Adam(lr=0.001), metrics=['accuracy'])

# Train the model with data augmentation
model.fit(datagen.flow(X_train, y_train, batch_size=32), steps_per_epoch=len(X_train) // 32, epochs=10, verbose=1)

# Unfreeze the last convolutional block of the base model for fine-tuning
for layer in base_model.layers[-5:]:
    layer.trainable = True

# Lower the learning rate for fine-tuning
model.compile(loss='binary_crossentropy', optimizer=Adam(lr=0.0001), metrics=['accuracy'])

# Train the model with fine-tuning
model.fit(datagen.flow(X_train, y_train, batch_size=32), steps_per_epoch=len(X_train) // 32, epochs=10, verbose=1)

# Make predictions on the test set
y_pred_probs = model.predict(X_test)
y_pred = (y_pred_probs > 0.5).astype(int)

# Calculate the F1 score
f1 = f1_score(y_test, y_pred)
print("F1 score:", f1)


Epoch 1/10


C:\Users\Naina\anaconda3\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:117: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


131/131 [==============================] - 562s 4s/step - loss: 0.6567 - accuracy: 0.7205
Epoch 2/10
131/131 [==============================] - 559s 4s/step - loss: 0.6045 - accuracy: 0.7298
Epoch 3/10
131/131 [==============================] - 546s 4s/step - loss: 0.5868 - accuracy: 0.7308
Epoch 4/10
131/131 [==============================] - 509s 4s/step - loss: 0.5836 - accuracy: 0.7306
Epoch 5/10
131/131 [==============================] - 509s 4s/step - loss: 0.5693 - accuracy: 0.7308
Epoch 6/10
131/131 [==============================] - 507s 4s/step - loss: 0.5677 - accuracy: 0.7301
Epoch 7/10
131/131 [==============================] - 531s 4s/step - loss: 0.5691 - accuracy: 0.7313
Epoch 8/10
131/131 [==============================] - 561s 4s/step - loss: 0.5627 - accuracy: 0.7306
Epoch 9/10
131/131 [==============================] - 559s 4s/step - loss: 0.5585 - accuracy: 0.7303
Epoch 10/10
131/131 [==============================] - 551s 4s/step - loss: 0.5564 - accuracy: 0.7308


KeyboardInterrupt: 

ResNet

In [79]:
import numpy as np
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.resnet50 import preprocess_input
from skimage.transform import resize

# Extract the feature matrix X and the label array y
X = df.drop('labels', axis=1).values
y = df['labels'].values

# Resize the images to (32, 32) to meet the minimum input size of ResNet50
X_resized = np.array([resize(img, (32, 32, 3)) for img in X])

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_resized, y, test_size=0.2, random_state=42)

# Create an ImageDataGenerator for data augmentation and preprocessing
datagen = ImageDataGenerator(
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True,
    preprocessing_function=preprocess_input
)

# Load the pre-trained ResNet50 model without the top layers
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(32, 32, 3))

# Create a new model on top of the pre-trained model
model = Sequential()
model.add(base_model)
model.add(GlobalAveragePooling2D())
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Fit the model using the data generator
model.fit(datagen.flow(X_train, y_train, batch_size=32),
          steps_per_epoch=len(X_train) // 32,
          epochs=10,
          verbose=1)

# Make predictions on the test set
y_pred_probs = model.predict(X_test)
y_pred = (y_pred_probs > 0.5).astype(int)

# Calculate the F1 score
f1 = f1_score(y_test, y_pred)
print("F1 score:", f1)


Epoch 1/10
131/131 [==============================] - 196s 1s/step - loss: 0.7034 - accuracy: 0.7027
Epoch 2/10
131/131 [==============================] - 140s 1s/step - loss: 0.5781 - accuracy: 0.7294
Epoch 3/10
131/131 [==============================] - 142s 1s/step - loss: 0.5704 - accuracy: 0.7301
Epoch 4/10
131/131 [==============================] - 158s 1s/step - loss: 0.5700 - accuracy: 0.7298
Epoch 5/10
131/131 [==============================] - 161s 1s/step - loss: 0.5632 - accuracy: 0.7306
Epoch 6/10
131/131 [==============================] - 168s 1s/step - loss: 0.5627 - accuracy: 0.7320
Epoch 7/10
131/131 [==============================] - 168s 1s/step - loss: 0.5627 - accuracy: 0.7337
Epoch 8/10
131/131 [==============================] - 158s 1s/step - loss: 0.5593 - accuracy: 0.7294
Epoch 9/10
131/131 [==============================] - 163s 1s/step - loss: 0.5602 - accuracy: 0.7298
Epoch 10/10
33/33 [==============================] - 7s 190ms/step
F1 score: 0.0


MobileNet

In [31]:
import numpy as np
from keras.applications.mobilenet import MobileNet, preprocess_input
from keras.models import Sequential
from keras.layers import Dense, GlobalAveragePooling2D
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from skimage.transform import resize
from keras.preprocessing.image import ImageDataGenerator

# Load your dataset and split it into training and testing sets
# X and y represent your dataset features and labels, respectively
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Resize the images to match the input shape of MobileNet
X_train_resized = np.array([resize(img, (224, 224, 3)) for img in X_train])
X_test_resized = np.array([resize(img, (224, 224, 3)) for img in X_test])

# Preprocess the input data
X_train_resized = preprocess_input(X_train_resized)
X_test_resized = preprocess_input(X_test_resized)

# Data augmentation
datagen = ImageDataGenerator(
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True
)
datagen.fit(X_train_resized)

# Load the pre-trained MobileNet model without the top layers
base_model = MobileNet(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

# Create a new model on top of the pre-trained model
model = Sequential()
model.add(base_model)
model.add(GlobalAveragePooling2D())
model.add(Dense(1, activation='sigmoid'))

# Freeze the layers of the pre-trained model
for layer in base_model.layers:
    layer.trainable = False

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model with data augmentation
model.fit(
    datagen.flow(X_train_resized, y_train, batch_size=32),
    steps_per_epoch=len(X_train_resized) // 32,
    epochs=10,
    validation_data=(X_test_resized, y_test)
)

# Unfreeze the last few layers of the base model for fine-tuning
for layer in base_model.layers[-5:]:
    layer.trainable = True

# Lower the learning rate for fine-tuning
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model with fine-tuning
model.fit(
    datagen.flow(X_train_resized, y_train, batch_size=32),
    steps_per_epoch=len(X_train_resized) // 32,
    epochs=10,
    validation_data=(X_test_resized, y_test)
)

# Predict labels for the test set
y_pred = model.predict(X_test_resized)
y_pred = np.round(y_pred).flatten()

# Calculate the F1 score
f1 = f1_score(y_test, y_pred)

print(f"F1 Score: {f1:.4f}")


Epoch 1/10
131/131 [==============================] - 101s 753ms/step - loss: 0.5975 - accuracy: 0.7049 - val_loss: 0.5694 - val_accuracy: 0.7438
Epoch 2/10
131/131 [==============================] - 91s 694ms/step - loss: 0.5813 - accuracy: 0.7306 - val_loss: 0.5691 - val_accuracy: 0.7438
Epoch 3/10
131/131 [==============================] - 92s 701ms/step - loss: 0.5804 - accuracy: 0.7301 - val_loss: 0.5704 - val_accuracy: 0.7438
Epoch 4/10
131/131 [==============================] - 91s 697ms/step - loss: 0.5789 - accuracy: 0.7306 - val_loss: 0.5632 - val_accuracy: 0.7438
Epoch 5/10
131/131 [==============================] - 90s 684ms/step - loss: 0.5756 - accuracy: 0.7310 - val_loss: 0.5609 - val_accuracy: 0.7438
Epoch 6/10
131/131 [==============================] - 91s 691ms/step - loss: 0.5766 - accuracy: 0.7303 - val_loss: 0.5596 - val_accuracy: 0.7438
Epoch 7/10
131/131 [==============================] - 90s 689ms/step - loss: 0.5736 - accuracy: 0.7306 - val_loss: 0.5636 - val_a